/* by pts@fazekas.hu at Fri Nov 25 02:32:23 CET 2022 */

.section	.note.GNU-stack,"",@progbits
.text

/* This is hand-written, and it is shorter than code generated by GCC 6.3.0. */
.globl	isalpha
.type	isalpha, @function
isalpha:  /* __attribute__((regparm(1))) int isalpha(int c); */
	orb $32, %al
	subb $97, %al
	cmpb $26, %al
	sbbl %eax, %eax
	negl %eax
	ret
.size	isalpha, .-isalpha
/* Test: int c; for (c = -1; c <= 255; ++c) { if (isalpha(c) != ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))) goto fail; } */
