/* by pts@fazekas.hu at Fri Nov 25 02:32:23 CET 2022 */

.section	.note.GNU-stack,"",@progbits
.text

/* This is hand-written, and it is shorter than code generated by GCC 6.3.0. */
.globl	isdigit
.type	isdigit, @function
isdigit:  /* __attribute__((regparm(1))) int isdigit(int c); */
	subb $48, %al
	cmpb $10, %al
	sbbl %eax, %eax
	negl %eax
	ret
.size	isdigit, .-isdigit
/* Test: int c; for (c = -1; c <= 255; ++c) { if (isdigit(c) != (c >= '0' && c <= '9')) goto fail; } */
