/* by pts@fazekas.hu at Fri Nov 25 02:32:23 CET 2022 */

.section	.note.GNU-stack,"",@progbits
.text

/* This is hand-written, and it is shorter than code generated by GCC 6.3.0. */
.globl	isspace
.type	isspace, @function
isspace:  /* __attribute__((regparm(1))) int isspace(int c); */
	subb $9, %al
	cmpb $13-9+1, %al
	jc .d2
	subb $32-9, %al
	cmpb $1, %al
.d2:	sbbl %eax, %eax
	negl %eax
	ret
.size	isspace, .-isspace
/* Test: int c; for (c = -1; c <= 255; ++c) { if (isspace(c) != ((c >= '\t' && c <= '\r') || c == ' ')) goto fail; } */
