/* by pts@fazekas.hu at Fri Nov 25 02:32:23 CET 2022 */

.section	.note.GNU-stack,"",@progbits
.text

/* This is hand-written, and it is shorter than code generated by GCC 6.3.0. */
.globl	isxdigit
.type	isxdigit, @function
isxdigit:  /* __attribute__((regparm(1))) int isxdigit(int c); */
	subb $48, %al
	cmpb $10, %al
	jc 1f
	orb $32, %al
	subb $49, %al
	cmpb $6, %al
1:	sbbl %eax, %eax
	negl %eax
	ret
.size	isxdigit, .-isxdigit
/* Test: int c; for (c = -1; c <= 255; ++c) { if (isxdigit(c) != ((c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F') || (c >= '0' && c <= '9'))) goto fail; } */
